# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: ume-linux
    ldflags:
      - -s -w -X main.version={{ .Version }} main.buildDate={{ .Date }} main.commitHash={{ .ShortCommit }}
    binary: ume
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
  - id: ume-win-amd64
    ldflags:
      - -s -w -X main.version={{ .Version }} main.buildDate={{ .Date }} main.commitHash={{ .ShortCommit }}
    binary: ume
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
  - id: ume-darwin
    ldflags:
      - -s -w -X main.version={{ .Version }} main.buildDate={{ .Date }} main.commitHash={{ .ShortCommit }}
    binary: ume
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: auguwu
    name: ume
