# 🐻‍❄️💐 ume: Easy, self-hostable, and flexible image host made in Rust
# Copyright 2021-2024 Noel Towa <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "ume"
description = "🐻‍❄️💐 Easy, self-hostable, and flexible image host made in Rust"
version = "4.0.0"
authors = ["Noel Towa <cutie@floofy.dev>"]
edition = "2021"
rust-version = "1.74.0"
repository = "https://github.com/auguwu/ume"

[[bin]]
name = "ume"
path = "./src/bin/ume.rs"

[features]
default = []
mimalloc = ["dep:mimalloc"]

[dependencies]
async-trait = "0.1.77"
aws-sdk-s3 = "1.15.0"
axum = { version = "0.7.4", features = ["macros"] }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
axum-server = { version = "0.6.0", features = ["tls-openssl"] }
azure_core = "0.19.0"
azure_storage = "0.19.0"
chrono = "0.4.31"
clap = { version = "4.5.1", features = ["derive", "env"] }
clap_complete = "4.5.1"
color-eyre = { version = "0.6.2", features = ["issue-url", "tracing-error"] }
dotenvy = "0.15.7"
eyre = "0.6.12"
hcl-rs = "0.16.7"
indicatif = "0.17.8"
mimalloc = { version = "0.1.39", optional = true }
mongodb = "2.8.1"
multer = "3.0.0"
noelware-config = { git = "https://github.com/Noelware/core-rs", rev = "fdbb253fd424de509eefaf5c740fc7feac75825f", version = "0.1.0", features = [
    "derive",
] }
noelware-log = { git = "https://github.com/Noelware/core-rs", rev = "fdbb253fd424de509eefaf5c740fc7feac75825f", version = "0.1.0", features = [
    "writers",
] }
noelware-remi = { git = "https://github.com/Noelware/core-rs", rev = "fdbb253fd424de509eefaf5c740fc7feac75825f", version = "0.1.0", features = [
    "all",
] }
noelware-serde = { git = "https://github.com/Noelware/core-rs", rev = "fdbb253fd424de509eefaf5c740fc7feac75825f", version = "0.1.0", features = [
    "tracing",
] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
owo-colors = "4.0.0"
rand = "0.8.5"
regex = "1.10.3"
remi = "0.5.0"
remi-azure = { version = "0.5.0", features = ["serde", "tracing"] }
remi-fs = { version = "0.5.0", features = ["serde", "tracing"] }
remi-gridfs = { version = "0.5.0", features = ["serde", "tracing"] }
remi-s3 = { version = "0.5.0", features = ["serde", "tracing"] }
sentry = "0.32.2"
sentry-tower = { version = "0.32.2", features = ["axum", "http"] }
sentry-tracing = "0.32.2"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["catch-panic"] }
tracing = "0.1.40"
tracing-indicatif = "0.3.6"
tracing-log = "0.2.0"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.18"
url = "2.5.0"
which = "6.0.0"

[build-dependencies]
chrono = "0.4.31"
rustc_version = "0.4.0"
which = "6.0.0"

[dev-dependencies]
syn = "2.0.49"
