# 🐻‍❄️💐 ume: Easy, self-hostable, and flexible image host made in Rust
# Copyright 2021-2024 Noel Towa <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "ume"
description = "🐻‍❄️💐 Easy, self-hostable, and flexible image host made in Rust"
version = "4.0.3"
authors = ["Noel Towa <cutie@floofy.dev>"]
edition = "2021"
rust-version = "1.76"
repository = "https://github.com/auguwu/ume"

[[bin]]
name = "ume"
path = "./src/bin/ume.rs"

[features]
default = []
mimalloc = ["dep:mimalloc"]

[dependencies]
# uses the fork until https://github.com/1Password/arboard/pull/134 is passed
# as of 12/04/24, it was merged but there is no version as of today (16/04/24)
#
# TODO(@auguwu): remove the git dependency once a new version is avaliable
arboard = { version = "3.3.2", git = "https://github.com/1Password/arboard", features = [
    "wayland-data-control",
] }
async-trait = "0.1.80"
aws-sdk-s3 = { version = "1.25.0", features = ["behavior-version-latest"] }
axum = { version = "0.7.5", features = ["macros"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
azalia = { git = "https://github.com/Noelware/core-rs", version = "0.1.0", rev = "f190efd883e61f0b630a14a5e1cc20da648fb38a" }
azure_storage = "0.19.0"
bson = "2.10.0"
cfg-if = "1.0.0"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive", "env"] }
clap_complete = "4.5.2"
color-eyre = { version = "0.6.3", features = ["issue-url", "tracing-error"] }
dotenvy = "0.15.7"
eyre = "0.6.12"
hcl-rs = "0.16.9"
humantime = "2.1.0"
image = "0.25.1"
mimalloc = { version = "0.1.41", optional = true }
mime = "0.3.17"
mongodb = { version = "2.8.2", features = ["tracing", "log"] }
multer = "3.1.0"
noelware-config = { git = "https://github.com/Noelware/core-rs", rev = "8eeb681c1efe1da8dc38504bf0c76e52ef543e32", version = "0.1.0", features = [
    "derive",
] }
noelware-log = { git = "https://github.com/Noelware/core-rs", rev = "8eeb681c1efe1da8dc38504bf0c76e52ef543e32", version = "0.1.0", features = [
    "writers",
] }
noelware-remi = { git = "https://github.com/Noelware/core-rs", rev = "8eeb681c1efe1da8dc38504bf0c76e52ef543e32", version = "0.1.0", features = [
    "all",
] }
noelware-serde = { git = "https://github.com/Noelware/core-rs", rev = "8eeb681c1efe1da8dc38504bf0c76e52ef543e32", version = "0.1.0", features = [
    "tracing",
] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
opentelemetry = "0.22.0"
opentelemetry-otlp = { version = "0.15.0", features = ["http-proto"] }
opentelemetry_sdk = "0.22.1"
owo-colors = "4.0.0"
rand = "0.8.5"
regex = "1.10.4"
remi = "0.7.1"
remi-azure = { version = "0.7.0", features = ["serde", "tracing"] }
remi-fs = { version = "0.7.1", features = ["serde", "tracing", "file-format"] }
remi-gridfs = { version = "0.7.1", features = ["serde", "tracing"] }
remi-s3 = { version = "0.7.1", features = ["serde", "tracing"] }
reqwest = { version = "0.12.4", features = ["multipart", "json"] }
sentry = "0.32.3"
sentry-tower = { version = "0.32.3", features = ["axum", "http"] }
sentry-tracing = "0.32.3"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["io-util"] }
tower-http = { version = "0.5.2", features = ["catch-panic"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = "0.3.18"
url = "2.5.0"
which = "6.0.1"

[build-dependencies]
chrono = "0.4.38"
rustc_version = "0.4.0"
which = "6.0.1"

[dev-dependencies]
quote = "1.0.36"
syn = "2.0.60"

[package.metadata.cargo-machete]
ignored = ["hcl-rs", "tracing-log"]
