name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.floofy.dev -u august --password-stdin
      - name: Build
        run: docker build -t registry.floofy.dev/auguwu/ume:${{github.sha}} .
      - name: Push
        run: docker push registry.floofy.dev/auguwu/ume:${{github.sha}}
  build-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u auguwu --password-stdin
      - name: Build
        run: make build-docker
      - name: Push
        run: make publish-docker
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Set image
        run: |
          kubectl set image deployment/ume ume=registry.floofy.dev/auguwu/ume:${{github.sha}}
      - name: Rollout status
        run: |
          kubectl rollout status deployment/ume
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: release!
        if: "contains(github.event.head_commit.message, 'release')"
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
