name: golangci
on:
  push:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'

  pull_request:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      # This is in a seperate workflow because if you run
      # it with Go installed before, it'll just error
      # :animePensive:
      #
      # https://i-am.floof.gay/images/1fdaa80a.png
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=1
          only-new-issues: false
