name: Lint on Pull Request
on:
  pull_request:
    branches:
      - 'feature/**'
      - 'bug/gh-**'
      - 'issue/gh-**'
      - staging
      - master

    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docker/**'
      - '.idea/**'
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod download && go get

      - name: Build project to see if it compiles
        run: make build

      - name: Format project for any formatting to apply
        run: make fmt
